[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services]
name = "builder-ai-tester"

[services.variables]
NODE_ENV = "production"
PORT = "8082"

[services.healthcheck]
path = "/health"
timeout = 30

# Resource limits
[services.resources]
memory = "2GB"
cpu = "1vCPU"

# Environment variables (to be set in Railway dashboard)
[services.env]
CLAUDE_API_KEY_1 = { required = true }
CLAUDE_API_KEY_2 = { required = false }
CLAUDE_API_KEY_3 = { required = false }
BUILDER_AI_MASTER_KEY = { required = true }
BUILDER_AI_INTERNAL_KEY = { required = true }
