[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.healthcheck]
path = "/health"
timeout = 30

# Resource limits
[services.resources]
memory = "2GB"
cpu = "1vCPU"

# Environment variables (to be set in Railway dashboard)
[services.env]
CLAUDE_API_KEY_1 = { required = false }
CLAUDE_API_KEY_2 = { required = false }
CLAUDE_API_KEY_3 = { required = false }
BUILDER_AI_MASTER_KEY = { required = false }
BUILDER_AI_INTERNAL_KEY = { required = false }
